# Generated by Django 4.2.6 on 2023-10-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(max_length=100, unique=True)),
                ('short_code', models.CharField(max_length=8, unique=True)),
            ],
        ),
    ]
